name: dask_course
channels:
  - conda-forge
  - bokeh
dependencies:
  - dask
  - dask-image
  - dask-ml
  - distributed
  - dask-jobqueue
  - pip
  - numpy
  - pandas
  - scikit-image
  - matplotlib
  - scipy
  - jupyter
  - jupyterlab>2.0.0
  - ipywidgets
  - jupyter-server-proxy
  - nodejs
  - bokeh
  - bokeh::jupyter_bokeh
  - python-graphviz
  - pip:
    - requests
    - dask_labextension
    - py7zr

#jupyter labextension install dask-labextension
#jupyter labextension install @jupyter-widgets/jupyterlab-manager
#jupyter labextension install @bokeh/jupyter_bokeh